type: "base" # base, update
username: "raphael-hao"
token: "ghp_xxxxxxxxxxxxxxxxxxxxxxxx"
base_image: "nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04" # or an existing brainstorm image
tag: "latest"
branch: "dy_routing_ae"
upload: true
update_brt: false
no_cache: false
context: ~