ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS base

ARG BRT_BRANCH=main
ARG UPDATE_BRT_ONLY
ENV BRT_BRANCH=${BRT_BRANCH}
ENV BRT_UPDATE_BRT_ONLY=${UPDATE_BRT_ONLY}
ENV DEBIAN_FRONTEND=noninteractive

COPY update_docker.sh /tmp/update_docker.sh

RUN bash /tmp/update_docker.sh --branch ${BRT_BRANCH} --brt_only ${BRT_UPDATE_BRT_ONLY}
