description: Distributed Test for Brainstorm

target:
  service: amlk8s
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # vc: resrchvc
  # resource_group: researchvc
  # workspace_name: resrchvc
  name: itplabrr1cl1

environment:
  image: raphael/brt:dist
  registry: resrchvc4cr.azurecr.io
  username: resrchvc4cr
  # setup:
    # The data will be downloaded to /tmp/ ONLY once per node.
    # - python download_pretrained_bert.py

# This example downloads the data on the fly.
# If you are interested in using the data in your Azure Blob, make sure to configure this section:
# storage:
#   data:
#     storage_account_name: gcrblob
#     container_name: data
#     mount_dir: /mnt/data

code:
  local_dir: $CONFIG_DIR/../sample/distributed
  # remote_dir: /root/code

env_defaults:
  USER: root

jobs:
  - name: brt_dist
    sku: G4-V100-IB
    submit_args:
      container_args:
        user: root
    command:
      # Note, please gives an unique job_name to avoid multiple jobs write to the same checkpoint file concurrently.
    - sleep 2h # sleep 10 minutes