MODEL:
  TYPE: swinv2_moe
  NAME: swinv2_moe_22182_64_patch4_window7_224_norm8log_cosine_s2it2_s3b1_gradS8_vitmoeloss_GwoN_bpr_cap2
  DROP_PATH_RATE: 0.4
  SWIN_V2_MOE:
    EMBED_DIM: 64
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 2, 4, 8, 16 ]
    WINDOW_SIZE: 7

    POSTNORM: True
    RELATIVE_COORDS_TABLE_TYPE: norm8_log
    ATTN_TYPE: cosine_mh
    RPE_OUTPUT_TYPE: sigmoid
    LN_TYPE: fp32

    MOE_BLOCKS: [ [ -1 ], [ -1 ], [ 1, 3, 5, 7, 9, 11, 13, 15, 17 ], [ 1 ] ]
    NORMALIZE_GATE: False
    BATCH_PRIORITIZED_ROUTING: True
    VITMOE_LOSS: True
    CAPACITY_FACTOR: 2.0
TRAIN:
  MOE_LOSS_WEIGHT: 0.01
  MOE_GRAD_SCALE: 8.0