base_base: "nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04" # or ghcr.io/raphael-hao/brt:latest
latest_base: "ghcr.io/raphael-hao/brt:latest"
branch: "osdi2023ae"
update_brt: false
no_cache: false
context: ~